config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  get '/about', to: 'welcome#about'

  get '/invite', to: 'invites#new'
  resources :invites , only: [:create]

  post 'add_user_to_group/:id' => 'groups#add_user_to_group', as: 'add_user_to_group'
  post 'add_rsvp_to_event/:id' => 'events#add_rsvp_to_event', as: 'add_rsvp_to_event'
  delete 'remove_user_from_group/:id' => 'groups#remove_user_from_group', as: 'remove_user_from_group'

  
  get '/first_group' => 'groups#first_group', as: 'first_group'
  get '/groups/:id/dashboard', to: 'groups#group_dashboard', as: 'group_dashboard'
  get '/popular_groups', to: 'groups#popular_groups', as: 'popular_groups'

  get '/events/new_event', to: 'events#new_event_from_nav', as: 'new_event_from_nav'

  resources :groups, except: [:index] do
    resources :events
  end

  get '/users/:id/profile', to: 'users#show', as: 'user_profile'
  get '/users/:id/dashboard', to: 'users#user_dashboard', as: 'user_dashboard'
  get '/users/:id/events', to: 'users#user_events', as: 'user_events'

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}

end

app/models/group.rb
class Group < ActiveRecord::Base
  include Sluggable

  has_many :memberships
  # belongs_to :user
  has_many :users, through: :memberships
  has_many :events
  has_many :invites

  validates :name, presence: true, uniqueness: true

  sluggable_column :name

  after_save :set_membership

  def upcoming_events
    Event.from_group(self).upcoming.most_recent
    # self.events.reject { |event| event.in_past? }
  end

  def past_events
    # Event.from_group(self).most_recent.reverse
    self.events.reject { |event| !event.in_past? }
  end

  private

    def set_membership
      @membership = Membership.create!(user_id: self.user_id, group_id: self.id)
      set_organizer_membership_role(@membership)
    end

    def set_organizer_membership_role(membership)
      @role = MembershipRole.new(membership_id: membership.id, role: 1)
      @role.save!
    end    
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, except: [:index, :first_group, :new, :create]
  before_action :authenticate_user!
  before_action :require_creator, only: [:edit, :update, :destroy]

  respond_to :html

  def add_user_to_group
    
    @membership = Membership.new
    @membership[:user_id] = current_user.id
    @membership[:group_id] = @group.id
    if Membership.where(group_id: @group.id, user_id: current_user.id).count <= 0
      @membership.save
      MembershipRole.new(membership_id: @membership.id, role: 0).save!
      respond_with(@membership) do |format|
        format.html { redirect_to user_dashboard_path(current_user), notice: "You have been added to #{@group.name}" }
      end
      GroupMailer.group_join_email(@group, current_user).deliver
    else
      redirect_to user_dashboard_path(current_user), notice: "You are already a member of #{@group.name}"
    end
  end

  def remove_user_from_group
    membership = current_user.memberships.find_by_group_id(@group.id)
    roles = membership.membership_roles
    roles.delete_all
    membership.destroy
    current_user.save!
    redirect_to user_dashboard_path(current_user), notice: "You are no longer a member of #{@group.name}."
  end

  def group_events
    @events = @group.events.all
  end

  def group_members
  end

  def group_invite
  end
  
  def first_group
    @group = Group.new
    respond_with(@group)
  end

  def group_dashboard
    @group ||= Group.find_by slug: params[:id]
    respond_with(@group)
  end

  def popular_groups
    @groups = Group.all.sort { |a,b| b.memberships.count <=> a.memberships.count }
  end

  # def index
  #   @groups = Group.all
  #   respond_with(@groups)
  # end

  def show
    @upcoming_events = @group.upcoming_events.sort_by &:starts_at
    @past_events = @group.past_events.sort_by(&:starts_at).reverse
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group[:user_id] = current_user.id
    if Group.find_by(name: @group.name).present?
      flash.now[:danger] = "That group name has already been taken."
      render 'new'
    else
      @group.save
      GroupMailer.group_create_email(@group, current_user).deliver
      respond_with(@group) do |format|
        format.html { redirect_to group_dashboard_path(@group) }
      end
    end
  end


  def update
    @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private

    def require_creator
      access_denied unless user_signed_in? && (current_user.id == @group.user_id)
    end

    def set_group
      @group = Group.find_by slug: params[:id]
    end

    def group_params
      params.require(:group).permit(:name, :description, :user_id)
    end
    
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= bootstrap_form_for(@group, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-7") do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.text_area :description %>
  </div>
  <div class="field">
      <%= hidden_field_tag(:user_id, current_user.id) %>
  </div>
  <div class="col-sm-offset-2">
    <div class="actions">
      <%= f.submit 'Submit', class:'btn btn-lg link-style dark br-custom-blue'%>
    </div>
  </div>
<% end %>
</div>

app/views/groups/_group_dashboard_events.html.erb
<div class="col-md-7">
  <div class="widget pages-widget"><!-- Pages widget -->
    <div class="widget-head br-custom-blue">
      <h2 class="table-title">Scheduled Events</h2>
    </div>
    
    <div class="widget-body no-padd">
      <div class="table-responsive">
        <table class="table table-bordered">
          <!-- Table heading -->
          <tr> 
            <!--<th><input type="checkbox"></th>-->
            <th>Event</th>
            <th>Date</th>
            <th>Location</th>
          </tr>
          <% @group.events.each do |event| %>
            <tr>
              <!--<td><input type="checkbox"></td>--><!-- Check box -->
              <td><%= link_to event.name, group_event_path(@group, event) %></td><!-- Event Name -->
              <td><%= pretty_datetime(event.starts_at) %></td><!-- Date -->
              <td><%= event.address %></td><!-- Location -->
            </tr>
          <% end %>
        </table>
      </div><!--/table-responsive-->
    </div><!--/widget-body-->
    
    <div class="widget-foot">
      <span class="pull-left">
        <%= link_to 'Create an Event', new_group_event_path(@group), class: "btn br-dark-blue sub-button create" %>
        
        <!--<a href="#" class="btn btn-default sub-button">Delete This Event</a>-->
      </span>
      
      <div class="clearfix"></div>
    </div><!-- /widget foot -->

  </div><!-- /pages widget -->
</div>

app/views/groups/_group_dashboard_members.html.erb
<div class="col-md-5">
  <!-- Contacts widget -->
  <div class="widget contacts-widget">
    
    <div class="widget-head br-custom-blue">
      <h2 class="table-title">Current Members</h2>
    </div>
    
    <div class="widget-body scroll">
      
      <ul class="list-unstyled">
        <div class="clearfix"></div>
        
          <% @group.users.each do |user| %>
            <li class="c-list">
              <!-- Contact pic -->
              <div class="contact-pic">
              <!--TODO: adjust for each member's avatar, not current_user-->
                <img src='<%= user.avatar_url %>' alt="" class="img-responsive img-circle">
              </div>
              <!-- Contact details -->
              <div class="contact-details">
                <!-- Contact name and number -->
                <div class="pull-left">
                  <strong><%= link_to user.first_name || user.email, user_profile_path(user) %></strong>
                  <small><%= user.phone_number || "Phone Number" %></small>
                </div>
                <!-- Call, Message and Email buttons -->
                <div class="pull-right">
                  <a href="#"><i class="fa fa-envelope fa-lg"></i></a>
                </div>
                <div class="clearfix"></div>
              </div>
            </li>
          <% end %>

      </ul>
    </div><!--/widget-body-scroll-->
    
    <div class="widget-foot">
      <h4 class="pull-left"><%= @group.users.size %> <%= "Member".pluralize(@group.users.size) %></h4>
      <%= link_to "Invite a Friend", invite_path(@group), class: "btn br-lgreen sub-button pull-right" %>
      <div class="clearfix"></div>
    </div>
    
  </div><!--/widget-->
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/first_group.html.erb
<div class="groups-background">
<div class="main-content">
  <div class="container">
    <div class="page-content">
  		<div>
          <h1 class="dash-title group">Welcome, <%= current_user.first_name || current_user.email %>!</h1>

          <hr />
          
          <p>To begin using your Start Charlotte account, create your first group below. <br /> 
          (You will be assigned the role of group administrator automatically upon submit). <br />
          Or, you can skip this step and go directly to your user dashboard.</p>

          <hr />
          
        	<h1 class="dash-title group">Create Your First Group</h1>
      
      </div>
      
      
        <div class="divider"></div>

  		  <div class="well well-lg">
            	
            	<%= render 'form' %>

              <!-- <div class="col-sm-3 col-sm-offset-2"> -->
              <%= link_to 'Skip this Step for Now >>', user_dashboard_path(current_user) %>
              <!-- </div> -->
          
		    </div><!--/well well-lg-->
	   </div><!--/page-content-->
  </div><!--/container-->

</div><!--/main-content-->
</div>

app/views/groups/group_dashboard.html.erb
<div class="main-content">
	<div class="container">
		
  		<div><h1 class="dash-title group"><i class="fa fa-chevron-right"></i>Admin Area: <%= @group.name %></h1></div>

      <div class="divider dark"></div>
			<div class="row">

				<%= render 'group_dashboard_events' %>

				<%= render 'group_dashboard_members' %>

			</div><!--/row-->
		
	</div><!--/container-->
</div><!--/main-content-->

app/views/groups/group_events.html.erb
<div class="main-content">
	<div class="container">
						
		<div class="page-content">
		
			<!-- Heading -->
			<h3 class="pull-left"><%= @group.name %>'s events:</h3>
			<div class="clearfix"></div>
      
      <div class="divider"></div>

      <div class="table-responsive">
        <table class="table table-bordered">
          <!-- Table heading -->
          <tr> 
            <th>Event Name</th>
            <th>Description</th>
            <th>RSVPS</th>
          </tr>
          <% @events.each do |event| %>
            <tr>
              <td><%= link_to "#{event.name}", group_events_path(event) %></td>
              <td><%= event.description %></td>
              <td><%= event.rsvps.count %></td>
            </tr>
          <% end %>
        </table>
      </div>
			
			
		</div>
		
	</div>
</div>

app/views/groups/group_invite.html.erb
<div class="main-content">
	<div class="container">
						
		<div class="page-content">
		
			<!-- Heading -->
			<div class="single-head">
				<!-- Heading -->
				<h3 class="pull-left">Send Invites to <%= @group.name %></h3>
				<div class="clearfix"></div>
			</div>
			
			
		</div>
		
	</div>
</div>

app/views/groups/group_members.html.erb
<div class="main-content">
	<div class="container">
						
		<div class="page-content">
		
			<!-- Heading -->
			<div class="single-head">
				<!-- Heading -->
				<h3 class="pull-left"><%= @group.name %>'s Members:</h3>
				<div class="clearfix"></div>
			</div>
			
			
		</div>
		
	</div>
</div>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<!-- <div class=""> --><!--put bkgd color here-->
  <div class="main-content">
    <div class="container">
      <div class="page-content">
    		<div>
          	<h1 class="dash-title group">Create a New Group</h1>
        	</div>
        
        	<div class="divider"></div>

  		    <div class="well well-lg">
            	
            	<%= render 'form' %>
              
          </div><!--/well well-lg-->
  	   </div><!--/page-content-->
    </div><!--/container-->
  </div><!--/main-content-->
</div><!--/background-->

app/views/groups/new_group.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/popular_groups.html.erb
<div class="main-content">
	<div class="container">
		<div>
			<h1 class="dash-title group">Popular STARTCLT Groups</h1>
		</div>
			
		<div class="divider"></div>
		
		<div class="">
			<div class="page-content">
				<table class="table table-hover">
					<thead class="br-black">
						<td class="white">GROUP NAME</td>
						<td class="text-center white">MEMBERS</td>
						<td class="text-center white">DATE CREATED</td>
					</thead>
						<tr><% @groups.each do |group| %></tr>
							<td><%= link_to group.name, group_path(group) %></td>
							<td class="text-center"><%= group.memberships.count %></td> 
							<td class="text-center"><%= group.created_at.strftime("%b %d, %Y") %></td>
						<% end %>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="city-bkgd"></div>

app/views/groups/show.html.erb
<div class="main-content">
	<div class="container">
		<div class="page-content">
			<div class="row">
				<!-- Heading -->
				<div class="col-sm-8">
					<% if !current_user.groups.include?(@group) %>
						<h1 class="dash-title group group-name">About <%= @group.name %></h1>
							<p><%= @group.description %></p>
						</div>
						<%= form_tag add_user_to_group_path(@group) do %>
						<button type="submit" class="btn btn-lg br-custom-blue link-style join pull-right">Join This Group</button>
						<% end %>
					
					<% else %>
					
						<%= form_tag remove_user_from_group_path(@group) do %>
							<h1 class="dash-title group group-name">About <%= @group.name %></h1>
							<p><%= @group.description %></p>
						</div>
							<%= link_to "Leave This Group", {:action => "remove_user_from_group"}, class: "btn btn-lg btn-default link-style dark pull-right", method: "delete", data: { confirm: "Are you sure?" } %>
						<% end %>
					<% end %>
			</div><!--/row-->
		</div><!--/page-content-->
	
	<br />

	<div class="page-content">

			<ul class="nav nav-tabs">
			  <li class="<%= 'active' if params[:tab].nil? %>">
			    <%= link_to "Upcoming Events (#{@group.upcoming_events.count})", group_path(@group) %>
			  </li>
			  <li class="<%= 'active' if params[:tab] == 'past' %>">
			    <%= link_to "Past Events (#{@group.past_events.count})", group_path(@group, tab: 'past') %>
			  </li>
			</ul>

		<br>

		<% if params[:tab].nil? %>
		  <% @upcoming_events.each do |event| %>
				<table class="table table-default">
					<tr>
						<td>
							<%= render "events/events_table", event: event %>
						</td>
					
						<td>
							<% if current_user.events.include?(event) %>
								<h3 class="attending pull-right">Attending</h3>
							<% else %>
								<h3><%= link_to "RSVP", add_rsvp_to_event_path(:rsvp_event_id => event.id, :event_name => event.name), class: "btn br-dark-blue link-style vert-cent pull-right", method: "post" %></h3>
							<% end %>
						</td>
					</tr>
				</table>
		  <% end %>

		<% elsif params[:tab] == 'past' %>
		  <% @past_events.each do |event| %>
				<table class="table table-default">
					<tr>
						<td>
							<%= render "events/events_table", event: event %>
						</td>
					
						<td>
							<% if current_user.events.include?(event) %>
								<h3 class="attending pull-right">Attended</h3>
							<% end %>
						</td>
					</tr>
				</table>
		  <% end %>
		<% end %>

		</div><!--/page-content-->
	</div><!--/container-->
</div><!--/main-content-->