config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  get '/about', to: 'welcome#about'

  get '/invite', to: 'invites#new'
  resources :invites , only: [:create]

  post 'add_user_to_group/:id' => 'groups#add_user_to_group', as: 'add_user_to_group'
  post 'add_rsvp_to_event/:id' => 'events#add_rsvp_to_event', as: 'add_rsvp_to_event'
  delete 'remove_user_from_group/:id' => 'groups#remove_user_from_group', as: 'remove_user_from_group'

  
  get '/first_group' => 'groups#first_group', as: 'first_group'
  get '/groups/:id/dashboard', to: 'groups#group_dashboard', as: 'group_dashboard'
  get '/popular_groups', to: 'groups#popular_groups', as: 'popular_groups'

  get '/events/new_event', to: 'events#new_event_from_nav', as: 'new_event_from_nav'

  resources :groups, except: [:index] do
    resources :events
  end

  get '/users/:id/profile', to: 'users#show', as: 'user_profile'
  get '/users/:id/dashboard', to: 'users#user_dashboard', as: 'user_dashboard'
  get '/users/:id/events', to: 'users#user_events', as: 'user_events'

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}

end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable

  sluggable_column :email

  before_validation :prep_email
  before_save :create_avatar_url

  has_many :memberships
  has_many :groups, through: :memberships
  has_many :rsvps
  has_many :events, through: :rsvps

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def member_of(group)
    self.groups.include? group
  end

  def organizer?(group)
    membership = group.memberships.find_by(user_id: self.id)
    membership.membership_roles.each do |r|
      return true if r.role == "organizer"
    end
    false
  end

  def organizer_groups
    self.groups.reject { |group| !self.organizer?(group) }
  end

  def upcoming_group_events
    events = Event.from_group(self.groups).upcoming.most_recent
    events = events.reject { |event| self.events.include? event }
  end

  def user_membership_role_at_group_join(group, user)
    membership = group.memberships.find_by(user_id: user.id)
    return membership_role = membership.membership_roles.first.role
  end

  def role(group)
    membership = group.memberships.find_by(user_id: self.id)
    membership.membership_roles.first.role
  end
  
	private
  	def prep_email
  		self.email = self.email.strip.downcase if self.email
  	end

  	def create_avatar_url
  		self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
  	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   #def create
    #super
    #binding.pry
    #UserMailer.welcome_email(@user).deliver
  #end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name, :bio, :city, :state, :phone_number]
  end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     "/first_group"
   end

   def after_update_path_for(resource)
      user_profile_path(resource)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!
  
  def user_dashboard
    @events = current_user.events.order("starts_at")
    @events = @events.reject { |event| event.in_past? }
  end

  def user_groups
  end

  def user_events
    @events = current_user.upcoming_group_events
  end

  # def user_profile
  # end

  def show
    render 'user_profile'
  end

  private

  def set_user
    @user = User.find_by slug: params[:id]
  end
end

app/views/users/_user_dashboard_events.html.erb
<div class="col-sm-6">
  <div class="widget pages-widget">
    <div class="widget-head br-black">
      <h2 class="link-style no-hov"><%= @events.count %> <%= "Event".pluralize(@events.count) %> You Are Attending</h2>
    </div>

    <div class="widget-body no-padd">
      <div class="table-responsive">
        <table class="table table-bordered">
          <% if current_user.rsvps.count >= 1 %>
            <!-- Table heading -->
            <tr> 
              <th>Event Title</th>
              <th>Date</th>
              <th>Location</th>
              <th>RSVPs</th>
            </tr>
            <% @events.each do |event| %>
              <tr>
                <td><strong><%= link_to event.name, group_event_path(event.group, event), class: "dark-blue" %></strong></td><!-- Event Name -->
                <td><%= pretty_datetime(event.starts_at) %></td><!-- Date -->
                <td><%= event.address %></td><!-- Location -->
                <td>
                  <% if event.rsvps.present? %>
                    <center><strong><%= event.rsvps.count %></strong></center>
                  <% else %>
                    <%= "RSVP" %>
                  <% end %>
                </td>
              </tr>  
            <% end %>
          <% else %>
            <center><strong>You haven't made any RSVPs yet.</strong></center>
          <% end %>
        </table>
      </div><!--/table-responsive-->
    </div><!--/widget-body-->

    <div class="widget-foot">
      <%= link_to 'Recommended Events', user_events_path , class: 'btn br-lgreen sub-button pull-left' %>
      <div class="clearfix"></div>
    </div><!-- /widget foot -->
    
  </div>
</div><!-- /col-md -->

app/views/users/_user_dashboard_groups.html.erb
<div class="col-sm-6">
  <!-- Pages widget -->
  <div class="widget pages-widget">
    
    <div class="widget-head br-black">
      <h2 class="link-style no-hov">Your Groups</h2>
    </div>
    
    <div class="widget-body no-padd">
      
      <div class="table-responsive">
        <table class="table table-bordered">
          <!-- Table heading -->
          <tr> 
            
            <th>Group Name</th>
            <th class="text-center">Members</th>
            <th class="text-center">Status</th>
          </tr>
          <% current_user.groups.each do |group| %>
            <tr>
              <!--<td class="text-center"><input type="checkbox"></td>-->
							<td><%= link_to group.name, group_path(group) %></td>
              <td class="text-center"><%= group.memberships.count %></td>
              <% if @user.role(group) %>
                <% if @user.role(group) == "member" %>
                  <td class="text-center"><span class="badge badge-success"><%= @user.role(group).upcase %></span></td>
                <% else %>
                  <td class="text-center"><span class="badge badge-orange"><strong><%= @user.role(group).upcase %></strong></span></td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
      
    </div>
    
    <div class="widget-foot">
      <span class="pull-left">
        <%= link_to 'Join Another Group', popular_groups_path, class: 'btn br-custom-blue sub-button' %>&nbsp; 
        <!-- <a href="#" class="btn btn-default sub-button">Leave This Group</a> -->
      </span>
      <div class="clearfix"></div>
    </div>
    
  </div>

</div>

app/views/users/user_dashboard.html.erb
<div class="main-content">
	<div class="container">
		<div><h1 class="dash-title user">Account Info For: <%= current_user.first_name || current_user.email %></h1></div>
      
      		<div class="divider"></div>
			<div class="row">

			<%= render 'user_dashboard_groups' %>
			
			<%= render 'user_dashboard_events' %>

		</div>
	</div>
</div>

app/views/users/user_events.html.erb
<div class="main-content">
	<div class="container">
		<div>
			<h1 class="dash-title user">Recommended Events For <%= current_user.first_name || current_user.email %>:</h3>
		</div>
			
		<div class="divider"></div>
		
		<div class="">
			<div class="page-content">
				<% if @events.count > 0 %>
				<table class="table table-bordered table-hover">
					<thead class="br-black">
						<td class="white">GROUP</td>
						<td class="white">EVENT</td>
						<td class="white">LOCATION</td>
						<td class="white">START TIME</td>
						<td class="text-center white">RSVPS</td>
						<td class="text-center white"></td>
					</thead>
						<tr><% @events.each do |event| %></tr>
							<% path = group_event_path(event.group, event) %>
							<td><%= link_to event.group.name, path %></td>
							<td><%= link_to event.name, path %></td>
							<td><%= link_to event.address, path %></td> 
							<td><%= link_to pretty_datetime(event.starts_at),path %></td>
							<td class="text-center"><%= link_to event.rsvps.count, path %></td>
							<td><%= link_to "RSVP", add_rsvp_to_event_path(:rsvp_event_id => event.id, :event_name => event.name), class: "btn br-lgreen link-style dark pull-right", method: "post" %></td>
						<% end %>
					<% else %>
						<h1><%= link_to "Join a group", popular_groups_path, class: "link-style-dark blue" %> to receive recommened events.</h1>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/users/user_profile.html.erb
<div class="main-content">
	<div class="container">
		<div class="page-content">
			<!-- Heading -->
			<div>
				<h1 class="dash-title user"><%= @user.first_name || @user.email %>'s Profile</h1>
			</div>
			
			<div class="divider"></div>
			
			<div class="row">
				
				<div class="col-sm-2">
					<img src='<%= @user.avatar_url %>' class="img-responsive img-thumbnail profile ">
				</div>

					<div class="col-sm-9 pull-left">
							<h4 class="profile-item"><strong>Name: </strong><%= "#{@user.first_name} #{@user.last_name}" %></h4>
							<h4 class="profile-item"><strong>Email:</strong> <%= @user.email %></h4>
							<h4 class="profile-item"><strong>City:</strong> <%= @user.city %></h4>
							<h4 class="profile-item"><strong>State:</strong> <%= @user.state %></h4>

							<h4 class="profile-item"><strong>Bio:</strong> <%= @user.bio %></h4>
							<h4 class="profile-item"><strong>Phone:</strong> <%= @user.phone_number %></h4>
						
						<div class="clearfix"></div>
					</div>
				</div><!--/row-->
				
				<div class="row">
					<div class="col-sm-9 col-sm-offset-2">
						<% if @user.id == current_user.id %>
							<%= link_to 'Edit Profile', edit_registration_path(@user), class: 'btn btn-lg br-custom-blue link-style dark' %>
						<% end %>
					</div>
				</div><!--/row-->

				<div class="clearfix"></div>
			
			</div><!--/single-head-->
		</div><!--/page-content-->
	</div><!--/container-->
</div><!--main-content-->