config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  get '/about', to: 'welcome#about'

  get '/invite', to: 'invites#new'
  resources :invites , only: [:create]

  post 'add_user_to_group/:id' => 'groups#add_user_to_group', as: 'add_user_to_group'
  post 'add_rsvp_to_event/:id' => 'events#add_rsvp_to_event', as: 'add_rsvp_to_event'
  delete 'remove_user_from_group/:id' => 'groups#remove_user_from_group', as: 'remove_user_from_group'

  
  get '/first_group' => 'groups#first_group', as: 'first_group'
  get '/groups/:id/dashboard', to: 'groups#group_dashboard', as: 'group_dashboard'
  get '/popular_groups', to: 'groups#popular_groups', as: 'popular_groups'

  get '/events/new_event', to: 'events#new_event_from_nav', as: 'new_event_from_nav'

  resources :groups, except: [:index] do
    resources :events
  end

  get '/users/:id/profile', to: 'users#show', as: 'user_profile'
  get '/users/:id/dashboard', to: 'users#user_dashboard', as: 'user_dashboard'
  get '/users/:id/events', to: 'users#user_events', as: 'user_events'

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}

end

app/models/event.rb
class Event < ActiveRecord::Base
  include Sluggable
  sluggable_column :name

  belongs_to :group
  has_many :rsvps
  has_many :users, through: :rsvps

  validates :name, presence: true

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  # true, false
  def in_past?
    starts_at < Time.now 
  end
  
  def self.from_group(group)
    where(group: group)
  end
  
  def self.upcoming(reference = Time.now)
    where("starts_at > ?", reference)
  end
  
  def self.most_recent
    order('starts_at ASC, created_at ASC')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_models, only: [:index, :destroy, :group_events, :add_rsvp_to_event]

  respond_to :html

  def add_rsvp_to_event
    @group = Group.find_by slug: params[:id]
    event_id = params[:rsvp_event_id]
    event_name = params[:event_name]
    @rsvp = Rsvp.new
    @rsvp[:user_id] = current_user.id
    @rsvp[:event_id] = event_id
    if Rsvp.where(event_id: event_id, user_id: current_user.id).count <= 0
      @rsvp.save
      respond_with(@rsvp) do |format|
        format.html { redirect_to user_dashboard_path(current_user), notice: "You have RSVP'd to #{event_name}." }
      end
    else
      redirect_to user_dashboard_path(current_user), notice: "You have already RSVP'd to #{event_name}."
    end
  end

  def new_event_from_nav
    @groups = current_user.organizer_groups
  end

  def index
    @events = @group.events.all
    respond_with(@events)
  end

  def show
    @group = Group.find_by slug: params[:group_id]
    @event = Event.find_by slug: params[:id]
    respond_with(@event)
  end

  def new
    @group = Group.find_by(slug: params[:group_id])
    @event = Event.new(group: @group)
    respond_with(@event)
  end

  def edit
    @group = Group.find_by slug: params[:group_id]
    @event = Event.find_by slug: params[:id]
  end

  def create
    @group = Group.find_by(slug: params[:group_id])
    @event = Event.new(event_params)
    @event.group_id = @group.id
    if @event.starts_at < Time.now
      flash.now[:danger] = "Event start time can't be in the past."
      render :new
    elsif @event.ends_at < @event.starts_at
      flash.now[:danger] = "Event end time must come after start time."
      render :new
    else
    @event.save
    # respond_with(@event)
    redirect_to @group, notice: "New event successfully created."
    end
  end

  def update
    @event = Event.find_by slug: params[:id]
    @group = Group.find_by slug: params[:group_id]
    @event.update(event_params)
    redirect_to group_dashboard_path(@group), notice: "Event information successfully updated."
    # respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  # def group_events
  #   @events = @group.events.all
  # end

  private
    def set_models
      set_group
      set_event
    end

    def set_group
      @group = Group.find_by slug: params[:id]
    end

    def set_event
      @event = Event.find_by slug: params[:id]
    end

    def event_params
      params.require(:event).permit(:group_id, :name, :description, :location, :starts_at, :ends_at, :address, :latitude, :longitude)
    end

    # def rsvp_params
    #   params.require(:rsvp).permit(:event_id, :user_id)
    # end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events_table.html.erb
<div class="row">
	<div class="col-sm-10">
		<h3 class="event-name"><strong><u><%= link_to event.name, group_event_path(@group, event), class: "link-style-dark" %></u></strong></h3>
		<p><%= event.description %></p>
		<br>
		<p><strong>When: &nbsp;</strong><%= pretty_datetime(event.starts_at) %></p>
		<p><strong>Where: </strong><%= event.address %></p>
	</div>
</div>

app/views/events/_form.html.erb
<%= bootstrap_form_for([@group, @event], layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-7") do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- This shouldn't allow an event to be changed to another group
  <div class="field">
    <%= f.collection_select :group_id, Group.all, :id, :name %>
  </div>
 -->
  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="actions">
    <!--<%= f.submit %>-->
    <%= f.submit 'Save Event Info', class: 'btn btn-lg br-dark-blue link-style col-sm-offset-2' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="main-content">
    <div class="container">
      <div class="page-content">
    		<div>
          	<h1 class="dash-title group">Editing Event For: <%= @group.name %></h1>
        	</div>
        
        	<div class="divider"></div>

  		    <div class="well well-lg">

			<%= render 'form' %>

			<br />

				<div class="row">
					<div class="col-sm-6 col-sm-offset-2">

						<!--<%= link_to 'View Updated Event', group_event_path, class: 'btn btn-default sub-button' %>-->
						<!--<%= link_to 'Return to Admin Area', group_dashboard_path(@group), class: 'btn btn-default sub-button' %>-->
					</div>
				</div>
			
			</div><!--/well well-lg-->
  	   </div><!--/page-content-->
    </div><!--/container-->
</div><!--/main-content-->

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Starts at</th>
      <th>Ends at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.group_id %></td>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.location %></td>
        <td><%= event.starts_at %></td>
        <td><%= event.ends_at %></td>
        <td><%= link_to 'Show', group_event_path(@group, event) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_group_event_path %>

app/views/events/new.html.erb
<div class="main-content">
    <div class="container">
      <div class="page-content">
    		<div>
          	<h1 class="dash-title group">Create a New Event For: <%= @group.name %></h1>
        	</div>
        
        	<div class="divider"></div>

  		    <div class="well well-lg">

				<%= render 'form' %>

			   </div><!--/well well-lg-->
  	   </div><!--/page-content-->
    </div><!--/container-->
</div><!--/main-content-->

app/views/events/new_event_from_nav.html.erb
<div class="main-content">
    <div class="container">
      <div class="page-content">
        <div>
            <h1 class="dash-title group">Choose a group for your new event:</h1>
          </div>
        
          <div class="divider"></div>

          <div class="well well-lg">
            <% @groups.each do |group| %>
              <p>
                <strong><u><%= link_to group.name, new_group_event_path(group), class: "link-style-dark" %></u></strong>
              </p>
            <% end %>
          </div><!--/well well-lg-->
       </div><!--/page-content-->
    </div><!--/container-->
</div><!--/main-content-->

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="main-content">
    <div class="container">
      <div class="page-content">
        <div>
            <h1 class="rsvp-count"><%= @event.rsvps.count %> <%= "RSVP".pluralize(@event.rsvps.count) %>  
            <h1 class="dash-title group"><%= @event.name %></h1>
            <h2 class="org-name"><%= @event.group.name %></h2>
        </div>

        <div class="divider"></div>
            <div class="row">
              <!--moved this to header-->
              <!-- <p><strong>Group: </strong><%= @event.group.name %></p> -->

              <!--moved this to header-->
              <!--<p><strong>Title:</strong><%= @event.name %></p>-->
                <div class="col-sm-2">
                  <p><strong>Description: </strong></p>
                </div>

                <div class="col-sm-8">  
                  <p><%= @event.description %></p>
                </div>
            </div><!--/row>-->

            <hr />

            <div class="row">
                <div class="col-sm-2 col-xs-2">
                  <p class="event-info"><strong>Event Starts: </strong></p>
                </div>
              
                <div class="col-sm-8">
                  <p class="event-info"><%= pretty_datetime(@event.starts_at) %></p>
                </div>
            </div><!--/row-->
              
            <div class="row">
                <div class="col-sm-2 col-xs-2">
                  <p class="event-info"><strong>Event Ends: </strong></p>
                </div>
                
                <div class="col-sm-8">
                  <p class="event-info"><%= pretty_datetime(@event.ends_at) %></p>
                </div>
            </div><!--/row-->

            <% if @event.address.present? %>
              <div class="row">
                <div class="col-sm-2 col-xs-2">
                  <p class="event-info"><strong>Address: </strong></p>
                </div>
                
                <div class="col-sm-8">
                  <p class="event-info"><%= @event.address %></p>
                </div>
              </div><!--/row-->
            
              <div class="col-sm-6 col-sm-offset-2">                
                <p class="map">
                  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}" %>
                </p>
              </div><!--/row-->

                          <% if @event.in_past? %>
              <h1 class="concluded pull-right">EVENT CONCLUDED</h1>
            <% end %>

            <% else %>

              <div class="row">
                <div class="col-sm-2 col-xs-2">
                  <p class="event-info"><strong>Address: </strong></p>
                </div>
                
                <div class="col-sm-8">
                  <p class="event-info"><%= @event.name %><%= " does not have a location specified yet." %></p>
                </div>
              </div><!--/row-->
            <% end %>

            <div class="row">
              <div class="col-sm-10 col-sm-offset-2">
                <% if current_user.member_of(@event.group) && current_user.organizer?(@event.group) %>
                  <%= link_to 'Edit This Event', edit_group_event_path, class: 'btn btn-default sub-button' %>
                  <%= link_to 'Back to Dashboard', group_dashboard_path(@group), class: 'btn btn-default sub-button' %>
                <% else %>
                  <%= link_to 'Back to Group Page', group_path(@group), class: 'btn btn-default sub-button' %>
                  <%= link_to 'User Dashboard', user_dashboard_path(current_user), class: 'btn btn-default sub-button' %>
                <% end %>
              </div>
          </div><!--/row-->
       </div><!--/page-content-->
    </div><!--/container-->
</div><!--/main-content-->