config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  get '/about', to: 'welcome#about'

  get '/invite', to: 'invites#new'
  resources :invites , only: [:create]

  post 'add_user_to_group/:id' => 'groups#add_user_to_group', as: 'add_user_to_group'
  post 'add_rsvp_to_event/:id' => 'events#add_rsvp_to_event', as: 'add_rsvp_to_event'
  delete 'remove_user_from_group/:id' => 'groups#remove_user_from_group', as: 'remove_user_from_group'

  
  get '/first_group' => 'groups#first_group', as: 'first_group'
  get '/groups/:id/dashboard', to: 'groups#group_dashboard', as: 'group_dashboard'
  get '/popular_groups', to: 'groups#popular_groups', as: 'popular_groups'

  get '/events/new_event', to: 'events#new_event_from_nav', as: 'new_event_from_nav'

  resources :groups, except: [:index] do
    resources :events
  end

  get '/users/:id/profile', to: 'users#show', as: 'user_profile'
  get '/users/:id/dashboard', to: 'users#user_dashboard', as: 'user_dashboard'
  get '/users/:id/events', to: 'users#user_events', as: 'user_events'

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 text-center">
        <hr>
        <p><%= link_to 'TTS CodePilots', about_path, class: 'link-style'%><span class="year">©2015</span></p>
        <p class="link-style"><a class="lightblue" href="#" title="Scroll to Top">Back to Top</a></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_group_side_bar.html.erb
<div class="sidebar group"><!-- Sidebar starts -->
  <div class="sidey">

    <div class="logo"><!-- Logo -->
      <h1><%= link_to 'Start CLT', user_dashboard_path(current_user) %></h1>
    </div>
    
    <div class="sidebar-dropdown"><a href="#" class="br-black"><i class="fa fa-bars"></i>Tasks</a></div><!-- Responsive dropdown -->

    <div class="side-nav"><!-- Sidebar navigation starts -->
      <div class="side-nav-block">
        <p class="link-style no-hov">Tasks</p>
        <ul class="list-unstyled">
          <li class="bordered blue"><%=link_to 'Create a Group', new_group_path, class: 'lightlink' %></li>
          <li class="bordered blue"><%=link_to 'Create an Event', new_event_from_nav_path, class: 'lightlink' %></li>
        </ul>
      </div>
    </div><!-- Sidebar navigation ends -->
    
  </div>
</div><!-- Sidebar ends -->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_new_sidenav.html.erb
<!-- Sidebar starts -->
<div class="sidebar">
	<div class="sidey">
	<!-- Logo -->
		<div class="logo">
			<h1><a href="index.html">Your Logo Here</a></h1>
		</div>
		
		<!-- Sidebar navigation starts -->
		
		<!-- Responsive dropdown -->
		<div class="sidebar-dropdown"><a href="#" class="br-red"><i class="fa fa-bars"></i>Menu</a></div>
		
		<div class="side-nav">
		
			<div class="side-nav-block">
				<!-- Sidebar heading -->
				<h4>Main</h4>
				<!-- Sidebar links -->
				<ul class="list-unstyled">
					<li><a href="index.html">Dashboard</a></li>
					<li><a href="widgets.html">Widget</a></li>
					<li><a href="charts.html"></i> Charts</a></li>
					<li><a href="ui.html">UI</a></li>
					<!-- Mainmenu with submenu -->
					<li class="has_submenu">
						<a href="#">Pages <span class="nav-caret fa fa-caret-down"></span></a>
						<!-- Submenu -->
						<ul class="list-unstyled">
							<li><a href="calendar.html">Calendar</a></li>
							<li><a href="errorlog.html">Error Logs</a></li>
							<li><a href="gallery.html">Gallery</a></li>
							<li><a href="invoice.html">Invoice</a></li>
							<li><a href="media.html">Media</a></li>
							<li><a href="posts.html">Posts</a></li>
							<li><a href="statement.html">Statement</a></li>
						</ul>
					</li>
					<li><a href="users.html"></i> Users</a></li>
					<!-- Mainmenu with submenu -->
					<li class="has_submenu">
						<a href="#">Forms <span class="nav-caret fa fa-caret-down"></span></a>
						<!-- Submenu -->
						<ul class="list-unstyled">
							<li><a href="form.html">General Form</a></li>
							<li><a href="form-validate.html">Validate Form</a></li>
							<li><a href="form-wizard.html">Wizard Form</a></li>
						</ul>
					</li>
					<!-- Mainmenu with submenu -->
					<li class="has_submenu">
						<a href="#">Tables <span class="nav-caret fa fa-caret-down"></span></a>
						<!-- Submenu -->
						<ul class="list-unstyled">
							<li><a href="tables.html">General Tables</a></li>
							<li><a href="tables-data.html">Data Table</a></li>
						</ul>
					</li>
					<!-- Mainmenu with submenu -->
					<li class="has_submenu">
						<a href="#">Mail <span class="nav-caret fa fa-caret-down"></span></a>
						<!-- Submenu -->
						<ul class="list-unstyled">
							<li><a href="inbox.html">Inbox</a></li>
							<li><a href="mail-read.html"> Mail Read</a></li>
							<li><a href="mail-write.html">Mail Compose</a></li>
						</ul>
					</li>
				</ul>
			</div>
			
			<div class="side-nav-block">
				<h4>Menu</h4>
				<ul class="list-unstyled">
					<li><a href="0-base.html" class="active"><i class="fa fa-desktop"></i> Blank Page</a></li>
					<li><a href="login.html"></i> Login</a></li>
					<li><a href="404.html">Error Page</a></li>
					<li><a href="grid.html"> Grids</a></li>
					<li><a href="lock.html">Lock</a></li>
				</ul>
			</div>
		</div>
		<!-- Sidebar navigation ends -->
	</div>
</div>
<!-- Sidebar ends -->

app/views/layouts/_new_topnav.html.erb
<!-- Mainbar starts -->
<div class="mainbar">
<!-- Mainbar head starts -->
	<div class="main-head">
 		<div class="container">
			<div class="row">
				<div class="col-sm-9">
				<!-- Page title -->
					<h3><%= @group.name %></h3>
				</div>
			<!--TODO: double check this breakpoint/visibility vs js for this-->
			<div class="col-sm-3">
				<!-- Head user -->
				<div class="head-user dropdown">
					<a href="#" data-toggle="dropdown" id="profile">
						<% if current_user %>
							<img src='<%= current_user.avatar_url %>' alt="" class="img-responsive img-circle"/>
						<!-- User name -->
						<!--TODO change to <%= current_user.first_name %>--> 
						<!--TODO Figure out fonts within Jim's config file- ASK-->
						<%= current_user.email %><i class="fa fa-caret-down"></i> 
						<% end %>
					</a>
						<!-- Dropdown -->
						<ul class="dropdown-menu" aria-labelledby="profile">
						    <li><a href="#">View/Edit Profile</a></li>
							<li><a href="#">Something Else</a></li>
							<li><a href="#">Something Else</a></li>
							<li class="divider"></li>
							<li><%=link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
						</ul>
					</div>
				</div>
			</div>	
		</div>
	</div>
	<!--Mainbar head ends -->

	<!-- main content begins -->
	<%= yield %>
	
</div>
<!-- Mainbar ends -->

app/views/layouts/_old_nav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">StartCharlotte</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                        <% if user_signed_in? %>
                          <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              </li>
        <% else %>
          <li>
              <%= link_to "Sign In", new_user_session_path %>
              </li>
              <li>
              <%= link_to "Sign Up", new_user_registration_path %>
              </li>
        <% end %>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <% if current_user.nil? %>
            <%= form_for(:user, :as => :user, :url => session_path("user"), html: {class: "navbar-form navbar-right"}) do |f| %>
              <div class="form-group">
                <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
              </div>
              <button type="submit" class="btn btn-success">Sign in</button>
              <%= link_to new_user_registration_path do %>
                  <button type="submit" class="btn btn-primary">Sign up</button>
              <% end %>
            <% end %>
          <% end %>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

app/views/layouts/_topnav.html.erb
<div class="main-head"><!-- Mainbar head starts -->
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-6">
        <h2><%= link_to "#{@group.name} Admin Area", group_dashboard_path(@group) rescue "" %></h2><!-- Page title -->
      </div>
    
      <div class="col-sm-4 col-sm-offset-1 hidden-xs">
        <div class="head-user dropdown pull-right"><!-- Head user -->
          <a href="#" data-toggle="dropdown" id="profile">
            <% if current_user %>
              <% if current_user.first_name && current_user.last_name %><!-- User Name -->
                <%= "#{current_user.first_name} #{current_user.last_name}" %>
              <% else %>
                <%= "#{current_user.email}" %>
              <% end %>
              <img src='<%= current_user.avatar_url %>' alt="" class="img-responsive img-circle"><!-- User image -->
            <% end %>
          </a>
          
          <ul class="dropdown-menu" aria-labelledby="profile"><!-- Dropdown -->
            <li><%= link_to 'View Profile', user_profile_path(current_user), class:'drop-style'%></li>
            <li><%= link_to 'Dashboard', user_dashboard_path(current_user), class:'drop-style'%></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, class:'drop-style',method: :delete %></li>
          </ul>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>	
  </div>
</div><!-- Mainbar head ends -->

app/views/layouts/_user_side_bar.html.erb
<div class="sidebar user"><!-- Sidebar starts -->
  <div class="sidey">
    <div class="logo"><!-- Logo -->
      <h1><%= link_to 'Start CLT', user_dashboard_path(current_user) %></h1>
    </div>

    <!-- Responsive dropdown -->
    <div class="sidebar-dropdown"><a href="#" class="br-red"><i class="fa fa-bars"></i>Menu</a></div>
    
    <div class="side-nav"><!-- Sidebar navigation starts -->
      <div class="side-nav-block">
        <p class="link-style no-hov">Tasks</p>
        <ul class="list-unstyled">
          <li class="bordered"><%= link_to "Create a Group", new_group_path, class: 'sidelink' %></li>
          <li class="bordered"><%= link_to "Create an Event", new_event_from_nav_path, class: 'sidelink' %></li>
        </ul>
      </div>
      
      <div class="side-nav-block">
        <p class="link-style no-hov">Other</p>
        <ul class="list-unstyled">
          <li class="bordered"><%= link_to "Popular Groups", popular_groups_path, class: 'sidelink' %></li>
          <li class="bordered"><%= link_to 'Suggested Events', user_events_path(current_user), class: 'sidelink' %></li>
          <li class="bordered"><%= link_to 'Your Profile', user_profile_path(current_user), class: 'sidelink' %></li>
        </ul>
      </div>
    </div><!-- Sidebar navigation ends -->
    
  </div>
</div><!-- Sidebar ends -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">
    <title><%= content_for(:title) || "CodePilots | StartCharlotte" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  </head>
  <body>
    <% unless current_page?(about_path) %>
      <% if !user_signed_in? || current_page?(root_path) || current_page?(new_user_registration_path) || current_page?(new_user_session_path) || current_page?(first_group_path) %>
        <%= render 'layouts/messages' %>

        <%= yield %>
      <% else %>
        <div class="outer">
          <%= render 'layouts/user_side_bar' %>
          <div class="mainbar">
            <%= render 'layouts/topnav' %>
            <%= render 'layouts/messages' %>
            <%= yield %>
            <!--<%= render 'layouts/footer' %>-->
          </div>
        </div>
      <% end %>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>